version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/MovieRatings
    depends_on:
      - db
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - .dbdata:/var/lib/mysql
    environment:
       MYSQL_DATABASE: 'movieratings'
       MYSQL_USER: 'nhi'
       MYSQL_PASSWORD: 'vo'
       MYSQL_ROOT_PASSWORD: 'root'
